import { formatCT } from '@/lib/utils/date'
import type { QRHistoryEntry, QRAnalyticsSummary } from '@/lib/data/qr'
import QRScanLogToggle from './QRScanLogToggle'

function sanitizeLabel(label: string): string {
  return label.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'qr-code'
}

function domainFromUrl(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return url
  }
}

export default function QRHistoryPanel({
  history,
  timezone,
  scanStats,
}: {
  history: QRHistoryEntry[]
  timezone: string
  scanStats: Map<string, QRAnalyticsSummary>
}) {
  return (
    <div className="mt-10">
      <div className="pb-4 border-b border-neutral-border dark:border-dark-border mb-4">
        <h2 className="text-lg font-semibold text-dark dark:text-dark-text">QR Code History</h2>
        <p className="text-sm text-mid-gray dark:text-dark-muted mt-0.5">
          All generated codes are saved and shared across your team. Capped at 50 entries.
        </p>
      </div>

      {history.length === 0 ? (
        <p className="py-8 text-center text-mid-gray dark:text-dark-muted text-sm">
          No QR codes generated yet.
        </p>
      ) : (
        <div className="bg-white dark:bg-dark-surface border border-divider dark:border-dark-border rounded-lg overflow-hidden">
          {history.map((row) => {
            const filenameBase = sanitizeLabel(row.label || domainFromUrl(row.url))
            return (
              <div
                key={row.id}
                className="flex items-start gap-4 py-4 px-4 border-b border-neutral-border dark:border-dark-border last:border-b-0 hover:bg-neutral-surface dark:hover:bg-dark-nav transition-colors border-l-4"
                style={{ borderLeftColor: 'var(--brand-primary)' }}
              >
                <div className="min-w-0 flex-1">
                  <p className="font-medium text-dark dark:text-dark-text text-sm">
                    {row.label || domainFromUrl(row.url)}
                  </p>
                  {row.banner_text && (
                    <p className="text-xs text-mid-gray dark:text-dark-muted mt-0.5">
                      <span className="font-medium text-dark dark:text-dark-text">Banner:</span>{' '}
                      {row.banner_text}
                    </p>
                  )}
                  <p className="text-xs text-mid-gray dark:text-dark-muted break-all mt-0.5">
                    {row.url}
                  </p>
                  <p className="text-xs text-mid-gray dark:text-dark-muted mt-0.5">
                    Generated by {row.created_by_admin?.name ?? 'Unknown'} · {formatCT(row.created_at, 'MMM d, yyyy h:mm a', timezone)}
                  </p>
                  {row.redirect_token ? (
                    (() => {
                      const stats = scanStats.get(row.id)
                      if (!stats || stats.scanCount === 0) {
                        return (
                          <p className="text-xs text-mid-gray dark:text-dark-muted mt-1">
                            No scans yet
                          </p>
                        )
                      }
                      const { scanCount, lastScannedAt, deviceBreakdown } = stats
                      const lastStr = lastScannedAt
                        ? formatCT(lastScannedAt, 'MMM d', timezone)
                        : null
                      const parts = [
                        `${scanCount} scan${scanCount !== 1 ? 's' : ''}`,
                        lastStr ? `Last: ${lastStr}` : null,
                        [
                          deviceBreakdown.mobile > 0 ? `Mobile ${deviceBreakdown.mobile}` : null,
                          deviceBreakdown.desktop > 0 ? `Desktop ${deviceBreakdown.desktop}` : null,
                          deviceBreakdown.tablet > 0 ? `Tablet ${deviceBreakdown.tablet}` : null,
                        ]
                          .filter(Boolean)
                          .join(' / '),
                      ]
                        .filter(Boolean)
                        .join(' · ')
                      return (
                        <>
                          <p className="text-xs text-mid-gray dark:text-dark-muted mt-1">
                            {parts}
                          </p>
                          <QRScanLogToggle events={stats.events} />
                        </>
                      )
                    })()
                  ) : (
                    <p className="text-xs text-mid-gray dark:text-dark-muted mt-1">
                      Analytics not available
                    </p>
                  )}
                </div>
                <div className="flex flex-col gap-1 items-end flex-shrink-0">
                  <a
                    href={`data:image/png;base64,${row.png_base64}`}
                    download={`${filenameBase}.png`}
                    className="text-xs font-medium hover:underline whitespace-nowrap"
                    style={{ color: 'var(--brand-primary)' }}
                  >
                    PNG
                  </a>
                  <a
                    href={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(row.svg)}`}
                    download={`${filenameBase}.svg`}
                    className="text-xs font-medium hover:underline whitespace-nowrap"
                    style={{ color: 'var(--brand-primary)' }}
                  >
                    SVG
                  </a>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
