import { formatCT } from '@/lib/utils/date'
import type { QRHistoryEntry } from '@/lib/data/qr'

function sanitizeLabel(label: string): string {
  return label.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'qr-code'
}

function domainFromUrl(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return url
  }
}

export default function QRHistoryPanel({ history }: { history: QRHistoryEntry[] }) {
  return (
    <div className="mt-10">
      <h2 className="text-lg font-bold text-dark dark:text-dark-text mb-3">Saved QR Codes</h2>

      {history.length === 0 ? (
        <p className="text-sm text-mid-gray dark:text-dark-muted">No QR codes generated yet.</p>
      ) : (
        <div className="bg-white dark:bg-dark-surface border border-divider dark:border-dark-border rounded-lg divide-y divide-divider dark:divide-dark-border">
          {history.map((row) => {
            const filenameBase = sanitizeLabel(row.label || domainFromUrl(row.url))
            return (
              <div key={row.id} className="p-4 flex items-center justify-between gap-4">
                <div className="min-w-0">
                  <p className="text-sm font-semibold text-dark dark:text-dark-text">
                    {row.label || domainFromUrl(row.url)}
                  </p>
                  <p className="text-sm text-mid-gray dark:text-dark-muted overflow-hidden text-ellipsis whitespace-nowrap max-w-xs">
                    {row.url}
                  </p>
                  <p className="text-xs text-mid-gray dark:text-dark-muted mt-1">
                    Generated by {row.created_by_admin?.name ?? 'Unknown'} · {formatCT(row.created_at, 'MMM d, yyyy h:mm a')}
                  </p>
                </div>
                <div className="flex gap-3 shrink-0">
                  <a
                    href={`data:image/png;base64,${row.png_base64}`}
                    download={`${filenameBase}.png`}
                    className="text-sm font-semibold text-brand-primary dark:text-brand-primary-mid hover:underline cursor-pointer"
                  >
                    PNG
                  </a>
                  <a
                    href={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(row.svg)}`}
                    download={`${filenameBase}.svg`}
                    className="text-sm font-semibold text-brand-primary dark:text-brand-primary-mid hover:underline cursor-pointer"
                  >
                    SVG
                  </a>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
